// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7BtRYYkU6_6Wg57Q2Z7n-vLt71y2R0Tk',
    appId: '1:810279860405:web:5399d33f55414b046526fc',
    messagingSenderId: '810279860405',
    projectId: 'exchangexpert-90518',
    authDomain: 'exchangexpert-90518.firebaseapp.com',
    storageBucket: 'exchangexpert-90518.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8EaMzJIn0kCcYpZiP1OYdoMRWtazFJTY',
    appId: '1:810279860405:android:0424492f7ab71db86526fc',
    messagingSenderId: '810279860405',
    projectId: 'exchangexpert-90518',
    storageBucket: 'exchangexpert-90518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu4G_VF2yTl1eVRKVj7ZV-5wR2oCk7SJw',
    appId: '1:810279860405:ios:722d0b8e22076cbf6526fc',
    messagingSenderId: '810279860405',
    projectId: 'exchangexpert-90518',
    storageBucket: 'exchangexpert-90518.appspot.com',
    androidClientId: '810279860405-hfc66lhs5l3qnd6kiqf2o31b11b6c27j.apps.googleusercontent.com',
    iosClientId: '810279860405-fk1g57tol42uee2i51hokmmpp1af0hs2.apps.googleusercontent.com',
    iosBundleId: 'com.ios.exchangeXpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu4G_VF2yTl1eVRKVj7ZV-5wR2oCk7SJw',
    appId: '1:810279860405:ios:c599df3b0956662a6526fc',
    messagingSenderId: '810279860405',
    projectId: 'exchangexpert-90518',
    storageBucket: 'exchangexpert-90518.appspot.com',
    androidClientId: '810279860405-hfc66lhs5l3qnd6kiqf2o31b11b6c27j.apps.googleusercontent.com',
    iosClientId: '810279860405-k4o68d6p1oerhgoic9t45r2iigcdbs23.apps.googleusercontent.com',
    iosBundleId: 'com.example.exchangeXpert.RunnerTests',
  );
}
